### ISSUE TITLE
ReadDir broken on Windows

### ISSUE THREAD

**Issue by LongHairedHacker** [masahiro331/go-ext4-filesystem#12]
Hi,

I just came across a bug, that is basically a followup to #2.

```
package main

import (
    "io"
    "log"
    "os"

    "github.com/masahiro331/go-ext4-filesystem/ext4"
)

func main() {
    f, err := os.Open("filesystem.ext4")
    if err != nil {
        log.Fatal(err)
    }

    info, _ := f.Stat()

    reader := io.NewSectionReader(f, 0, info.Size())

    filesystem, err := ext4.NewFS(*reader, nil)
    if err != nil {
        log.Fatal(err)
    }

    _, err := filesystem.ReadDir("/foo/bar/");
    fmt.Printf("Error: %s", err)
}
```

Assuming `filesystem` has the necessary directory `/foo/bar` this will work fine under Linux, but fail with `file does not exist` under windows.

I did some investigating, and I was able to track down the issue to the use of `filepath.Clean`  in https://github.com/masahiro331/go-ext4-filesystem/blob/main/ext4/fs.go#L108C2-L108C69

Under linux `filepath.Clean("/foo/bar/")` returns `/foo/bar` and under windows you get `\foo\bar`.
Since the code then tries to split at `/` it fails under windows and ends up with a single element list.

I would love to provide you with a PR, but I'm not entirely sure what's the best solution here.

One solution might be to remove the `filepath.Clean`. However that would possible cause new issues when weird or malformed paths are provided as input to ReadDir.

An alternative solution would be to use `filepath.Separator` instead  "/" once `filepath.Clean` has been applied.

**Comment by LongHairedHacker** [comment]
I've just noticed a third option: https://pkg.go.dev/path/filepath#ToSlash 

`filepath.ToSlash(filepath.Clean("/foo/bar/"))` has the same output on both operating systems.

**Comment by mappu** [comment]
Another option is to use path.Clean() instead of filepath.Clean(), the path package always works with forwardslashes.
